### PR TITLE
modified categories taxonomy

### PR DESCRIPTION
**Pull request by sidkhuntia**
Screen Shot 2021-12-05 at 23 25 05

padding is less as other items in the theme have less padding.
And only #eef3ea was available for color choice

### CODE REVIEW

**Comment by chirag828049** [comment]
@sidkhuntia feel free to use more padding as most of the theme is currently in development and the pages are not edited.
I will merge the PR once coding period starts.

**Comment by sidkhuntia** [comment]
Okay, i think the padding is good enough or shall i change things ?

**Comment by sidkhuntia** [comment]
i have also tried these 
Screenshot from 2021-12-06 16-16-00
Screenshot from 2021-12-06 16-16-42

**Comment by chirag828049** [comment]
Out of the 2, the top design looks good (not the pipe separator though). Instead we can remove the pipe, give a different color to the number and make it bold. 
Also, can you please try changing the background color ?

**Comment by sidkhuntia** [comment]
Screen Shot 2021-12-07 at 15 52 04

how about these ?

**Comment by chirag828049** [comment]
Great work. merging changes.

**Pull request merged**
