### PR TITLE
Issues #25 and #22 is done. #25-Resume should be opened in new tab. #22.List Styling is Done in Blog listing page.

### PR DESCRIPTION
**Pull request by NotRohanPaul**

### CODE REVIEW

**Comment by rajivharlalka** [comment]
It would be better if you would have made seperate pull requests for different Issues, nevermind looking into this.

**Comment by rajivharlalka** [comment]
LGTM...

**Comment by chirag828049** [comment]
can you please add a screenshot of how it looks now ?

**Comment by NotRohanPaul** [comment]
Capture2
#22

**Comment by NotRohanPaul** [comment]
Capture
#25

**Comment by chirag828049** [comment]
Great work. Thanks. Merging this.

**Pull request merged**
